version: "3.9"

services:
  nginx:
    volumes:
      - ../../Proxy/gateway/nginx/conf.d:/etc/nginx/conf.d
      - ../../Proxy/assets:/var/www/assets
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
      - NGINX_PORT=80
    ports:
      - "80:80"

  postgres:
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  pgadmin4:
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "8001:80"

  redis:
    ports:
      - "6380:6379"

  identityserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5002
      - SpaUrl=http://www.alevelwebsite.com
      - CatalogApi=http://www.alevelwebsite.com:5000
      - BasketApi=http://www.alevelwebsite.com:5003
    ports:
      - "5002:5002"

  catalog.api:
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - Authorization__Authority=http://www.alevelwebsite.com:5002
      - ConnectionString=server=www.alevelwebsite.com;port=5433;database=catalog;uid=postgres;password=postgres;
      - PathBase=http://www.alevelwebsite.com:5000
    ports:
      - "5000:5000"

  basket.api:
    depends_on:
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5003
      - Authorization__Authority=http://www.alevelwebsite.com:5002
      - Redis__Host=www.alevelwebsite.com:6380
      - Redis__CacheTimeout=48:00:00
      - PathBase=http://www.alevelwebsite.com:5003
    ports:
      - "5003:5003"
